import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider, background, Image, Card, Text } from "@chakra-ui/react";
import { Main } from "next/document";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <ChakraProvider>
         <main>
          <Card
        direction={{ base: "column", sm: "row" }}
        overflow="hidden"
        variant="outline"
        backgroundColor="green.500"
        
      >
        <Image
          src="/photo/logo/Your BNb.png"
          alt="Beach logo"
          height="100px"
          width="100px"
          display="flex"
          mr={10}
        />
        <Text
          color="white"
          fontFamily="cursive"
          fontSize="xx-large"
          textAlign="center"
          justifyContent="center"
          alignItems="center"
          display="flex"
          flexDirection="column"
        >
          "Welcome to BnB: Your Home Away From Home" !!
        </Text>
      </Card>
          
          {children}
          </main>
        </ChakraProvider>
        
        </body>
    </html>
  );
}
