import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider, background } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <ChakraProvider>
        <header
            style={{
              backgroundColor: "green",
              padding: "1rem",
            }}>
              <p></p>
          </header>
          {children}
          <footer 
         style={{
          backgroundColor: "green",
          padding: "1rem",
        }}>
          <p></p>
        </footer>
        </ChakraProvider>
        
        </body>
    </html>
  );
}
